### ISSUE TITLE
Client disconnect shows "Error" in console

### ISSUE THREAD

**Issue by Guillaume351** [iTXTech/Synapse#11]
0.15.0
Hello,
When I disconnect from the server, the Synapse console shows : 

> [08:07:22] [Server thread/NOTICE]: Received Heartbeat Packet from 127.0.0.1:61185
> [08:07:27] [Server thread/NOTICE]: Received Heartbeat Packet from 127.0.0.1:61185
> [08:07:31] [Server thread/INFO]: WafflyDiamond18[/192.168.0.17:19132] [ClientID: 4933693591240844680] logged in
> [08:07:31] [Server thread/INFO]: WafflyDiamond18 has been transferred to 127.0.0.1:61185
> [08:07:32] [Server thread/NOTICE]: Received Heartbeat Packet from 127.0.0.1:61185
> [08:07:37] [Server thread/NOTICE]: Received Heartbeat Packet from 127.0.0.1:61185
> [08:07:39] [Server thread/ERROR]: Error RedirectPacket
> [08:07:42] [Server thread/NOTICE]: Received Heartbeat Packet from 127.0.0.1:61185
> C[08:07:47] [Server thread/NOTICE]: Received Heartbeat Packet from 127.0.0.1:61185

(Disconnecting at [08:07:39])
Even if it does not problem for other players, if you run this on a large network you need to know when there is a real error.
Thanks

**Comment by PeratX** [comment]
This is because player already logout and Genisys continued to send packets.

**Comment by PeratX** [comment]
Fixed, use the latest Genisys.
