### ISSUE TITLE
Plugin loading call undefined events

### ISSUE THREAD

**Issue by Guillaume351** [iTXTech/Synapse#12]
Hello,
when you load a plugin on Synapse, the PluginEnableEvent is called but it's undefined.
This event should be added or removed from the plugin loading (in FolderPluginLoader.php and PluginLoader.php).
Same for PluginUnloadEvent
Thanks

**Comment by ishitatsuyuki** [comment]
No description. Closing.

**Comment by Guillaume351** [comment]
@ishitatsuyuki Added, sorry I misscliked before writing description

**Comment by gaoyichuan** [comment]
I think plugins should be loaded on Genisys servers, not the Synapse server

**Comment by Guillaume351** [comment]
@gaoyichuan I use a plugin to update total player number and server name, it works fine as long as I remove those events

**Comment by XFuryMCPE** [comment]
https://github.com/iTXTech/Synapse/pull/14
