### ISSUE TITLE
[HELP] Phar Synapse

### ISSUE THREAD

**Issue by Dark111** [iTXTech/Synapse#13]
Sorry for post this in issue .

Hii , You have phar or you can help me to make Synapse in .phar.
And yes I am going to Gitter but nobody help me so I asked for help here . Please help me his ! : /

**Comment by gaoyichuan** [comment]
As you can see, the /ms command is still there. So run '/ms' either in game or in the console

**Comment by Dark111** [comment]
Ok thanks , how to /ms special file ?

**Comment by gaoyichuan** [comment]
See the help of the command

**Comment by Dark111** [comment]
help of the command /ms : Make PocketMine Phar.
