### ISSUE TITLE
Broken Pipe ?

### ISSUE THREAD

**Issue by Guillaume351** [iTXTech/Synapse#22]
Hello,
when some players join, I get this error : 

> [07:51:08] [SynapseServer thread/DEBUG]: #2 /src/synapse/network/synlib/ClientManager(42): synapse\network\synlib\ClientManager->tickProcessor()
> [07:51:08] [SynapseServer thread/DEBUG]: #3 /src/synapse/network/synlib/ClientManager(38): synapse\network\synlib\ClientManager->run()
> [07:51:08] [SynapseServer thread/DEBUG]: #4 /src/synapse/network/synlib/SynapseServer(90): synapse\network\synlib\ClientManager->__construct(synapse\network\synlib\SynapseServer object, synapse\network\synlib\SynapseSocket object)
> [07:51:08] [SynapseServer thread/DEBUG]: #5 (): synapse\network\synlib\SynapseServer->run()
> [07:51:08] [Server thread/NOTICE]: Received Heartbeat Packet from 127.0.0.1:48996
> [07:51:08] [Server thread/NOTICE]: Received Heartbeat Packet from 62.210.188.67:51428
> [07:51:08] [Server thread/ERROR]: Error RedirectPacket
> [07:51:08] [Server thread/ERROR]: Error RedirectPacket
> [07:51:08] [Server thread/ERROR]: Error RedirectPacket
> [07:51:08] [Server thread/ERROR]: Error RedirectPacket
> [07:51:08] [Server thread/ERROR]: Error RedirectPacket
> [07:51:08] [Server thread/ERROR]: Error RedirectPacket
> [07:51:08] [Server thread/ERROR]: Error RedirectPacket
> [07:51:08] [Server thread/ERROR]: Error RedirectPacket
> [07:51:08] [Server thread/ERROR]: Error RedirectPacket
> [07:51:08] [Server thread/ERROR]: Error RedirectPacket
> [07:51:08] [Server thread/ERROR]: Error RedirectPacket
> [07:51:08] [Server thread/ERROR]: Error RedirectPacket
> [07:51:08] [Server thread/ERROR]: Error RedirectPacket
> [07:51:08] [Server thread/ERROR]: Error RedirectPacket
> [07:51:08] [Server thread/ERROR]: Error RedirectPacket
> [07:51:08] [Server thread/ERROR]: Error RedirectPacket
> [07:51:08] [Server thread/ERROR]: Error RedirectPacket
> [07:51:08] [Server thread/ERROR]: Error RedirectPacket
> [07:51:08] [Server thread/ERROR]: Error RedirectPacket
> [07:51:08] [Server thread/ERROR]: Error RedirectPacket
> [07:51:08] [Server thread/ERROR]: Error RedirectPacket
> [07:51:09] [Server thread/INFO]: tyleriscool277[/204.115.6.185:52138] [ClientID: -6320520429774534432] logged in
> [07:51:09] [Server thread/INFO]: tyleriscool277 has been transferred to 62.210.188.67:51417
> [07:51:13] [SynapseServer thread/DEBUG]: An E_WARNING error happened: "socket_write(): unable to write to socket [32]: Broken pipe" in "/src/synapse/network/synlib/ClientConnection" at line 66
> [07:51:13] [SynapseServer thread/DEBUG]: #0 /src/synapse/network/synlib/ClientManager(78): synapse\network\synlib\ClientConnection->update()
> [07:51:13] [SynapseServer thread/DEBUG]: #1 /src/synapse/network/synlib/ClientManager(48): synapse\network\synlib\ClientManager->tick()
> [07:51:13] [SynapseServer thread/DEBUG]: #2 /src/synapse/network/synlib/ClientManager(42): synapse\network\synlib\ClientManager->tickProcessor()
> [07:51:13] [SynapseServer thread/DEBUG]: #3 /src/synapse/network/synlib/ClientManager(38): synapse\network\synlib\ClientManager->run()
> [07:51:13] [SynapseServer thread/DEBUG]: #4 /src/synapse/network/synlib/SynapseServer(90): synapse\network\synlib\ClientManager->__construct(synapse\network\synlib\SynapseServer object, synapse\network\synlib\SynapseSocket object)
> [07:51:13] [SynapseServer thread/DEBUG]: #5 (): synapse\network\synlib\SynapseServer->run()
> [07:51:13] [Server thread/NOTICE]: Received Heartbeat Packet from 127.0.0.1:48996
> [07:51:13] [Server thread/NOTICE]: Received Heartbeat Packet from 62.210.188.67:51428
> [07:51:18] [SynapseServer thread/DEBUG]: An E_WARNING error happened: "socket_write(): unable to write to socket [32]: Broken pipe" in "/src/synapse/network/synlib/ClientConnection" at line 66
> [07:51:18] [SynapseServer thread/DEBUG]: #0 /src/synapse/network/synlib/ClientManager(78): synapse\network\synlib\ClientConnection->update()
> [07:51:18] [SynapseServer thread/DEBUG]: #1 /src/synapse/network/synlib/ClientManager(48): synapse\network\synlib\ClientManager->tick()
> [07:51:18] [SynapseServer thread/DEBUG]: #2 /src/synapse/network/synlib/ClientManager(42): synapse\network\synlib\ClientManager->tickProcessor()
> [07:51:18] [SynapseServer thread/DEBUG]: #3 /src/synapse/network/synlib/ClientManager(38): synapse\network\synlib\ClientManager->run()
> [07:51:18] [SynapseServer thread/DEBUG]: #4 /src/synapse/network/synlib/SynapseServer(90): synapse\network\synlib\ClientManager->__construct(synapse\network\synlib\SynapseServer object, synapse\network\synlib\SynapseSocket object)
> [07:51:18] [SynapseServer thread/DEBUG]: #5 (): synapse\network\synlib\SynapseServer->run()
> [07:51:18] [Server thread/NOTICE]: Received Heartbeat Packet from 127.0.0.1:48996
> [07:51:18] [Server thread/NOTICE]: Received Heartbeat Packet from 62.210.188.67:51428
> [07:51:22] [Server thread/INFO]: ZacharyTheKillar[/12.156.170.35:19132] [ClientID: 7999518872972868152] logged in
> [07:51:22] [Server thread/INFO]: ZacharyTheKillar has been transferred to 62.210.188.67:51428
> [07:51:23] [Server thread/INFO]: proelgatogamer[/181.160.100.23:19132] [ClientID: 8515962150691197714] logged in
> [07:51:23] [Server thread/INFO]: proelgatogamer has been transferred to 62.210.188.67:51428
> [07:51:23] [SynapseServer thread/DEBUG]: An E_WARNING error happened: "socket_write(): unable to write to socket [32]: Broken pipe" in "/src/synapse/network/synlib/ClientConnection" at line 66
> [07:51:23] [SynapseServer thread/DEBUG]: #0 /src/synapse/network/synlib/ClientManager(78): synapse\network\synlib\ClientConnection->update()
> [07:51:23] [SynapseServer thread/DEBUG]: #1 /src/synapse/network/synlib/ClientManager(48): synapse\network\synlib\ClientManager->tick()
> [07:51:23] [SynapseServer thread/DEBUG]: #2 /src/synapse/network/synlib/ClientManager(42): synapse\network\synlib\ClientManager->tickProcessor()
> [07:51:23] [SynapseServer thread/DEBUG]: #3 /src/synapse/network/synlib/ClientManager(38): synapse\network\synlib\ClientManager->run()
> [07:51:23] [SynapseServer thread/DEBUG]: #4 /src/synapse/network/synlib/SynapseServer(90): synapse\network\synlib\ClientManager->__construct(synapse\network\synlib\SynapseServer object, synapse\network\synlib\SynapseSocket object)
> [07:51:23] [SynapseServer thread/DEBUG]: #5 (): synapse\network\synlib\SynapseServer->run()
> [07:51:23] [Server thread/NOTICE]: Received Heartbeat Packet from 127.0.0.1:48996
> [07:51:23] [Server thread/NOTICE]: Received Heartbeat Packet from 62.210.188.67:51428

If you need more details tell me

**Comment by PeratX** [comment]
We do not suggest use different servers.

**Comment by Guillaume351** [comment]
@PeratX It was the same server, I just tried to use the external ip. But if in the future I want to use the proxy between different servers in the same datacenter, synapse won't support it ? I think this issue should be investigated, except if you don't want to support this. Thanks
