### ISSUE TITLE
freeze on tap the pause button (synapse only)

### ISSUE THREAD

**Issue by dries-c** [iTXTech/Synapse#23]

**Comment by tigerza117** [comment]
Yes, i have the same problem too

**Comment by PeratX** [comment]
Pause?

**Comment by dries-c** [comment]
no freeze
its dont stop freezing

**Comment by MattWAnderson** [comment]
I csn report same issue.

When users go back to pause menu the whole client will freeze on them. For sure Win10 every time.

**Comment by tigerza117** [comment]
android and ios with

**Comment by tigerza117** [comment]
By sending a packet too big blazon.

**Comment by PeratX** [comment]
Do nothing with synapse, it just redirect all packets

**Comment by MattWAnderson** [comment]
Error only occurs on servers when a player is redirected to a client server and plays a short period. I will try to get a screen capture later of both server consoles as it happens.

**Comment by tigerza117** [comment]
i work for me https://github.com/iTXTech/Genisys/pull/1429

**Comment by tigerza117** [comment]
https://github.com/iTXTech/Synapse/commit/9e5d2070c5ec392060c800f8aac4f53ffe1706b7

WOW

**Comment by dries-c** [comment]
Ok i will test

**Comment by tigerza117** [comment]
THx @PeratX

**Comment by kabluinc** [comment]
Still happening after update after like 1-2 hours of server running
