### ISSUE TITLE
Can you add total players display in MOTD?

### ISSUE THREAD

**Issue by ghost** [iTXTech/Synapse#28]
i want to show total player of network server in motd. how i can. sorry my bad english

**Comment by PepbookPvP** [comment]
Hmm...Enhancement?

**Comment by ghost** [comment]
sorry i dont understand.

**Comment by PepbookPvP** [comment]
= =If you want to use a plugin I think it can be.Why not try?I didn't see the title,sorry.

**Comment by ghost** [comment]
i tred but plugins total slot not working

**Comment by PepbookPvP** [comment]
But why do you want to open an issue?

**Comment by PepbookPvP** [comment]
Now you can change the title to "Can you add total players display in MOTD?"

**Comment by PepbookPvP** [comment]
:)

**Comment by PepbookPvP** [comment]
And that's an enhancemant, so wait for developers' reply:)

**Comment by ghost** [comment]
okey i will wait :)

**Comment by Guillaume351** [comment]
With a plugin it works ;)

**Comment by ghost** [comment]
when a use plugins, it is not working

**Comment by Guillaume351** [comment]
I do use a plugin, so I know it works 😅

**Comment by ghost** [comment]
> plugins dont work. developers pls help me !

**Comment by Leejit** [comment]
@Guillaume351 can u contact me somehow and help me understand how I can be a part of testing this new addition to Genisys' amazing work? I'd also like to know how you link slots. Thank you in advance for any help you may offer.

**Comment by PeratX** [comment]
Synapse itself will show the total player.

**Comment by Guillaume351** [comment]
@LordJoshie "Somehow" ?  :') Contact me on twitter (@Guillaume351) or give me your mail

**Comment by Leejit** [comment]
Hey @Guillaume my email is jawshawa.p@gmail.com

Thank you in advance again, for the help I may receive.

**Comment by ghost** [comment]
@Guillaume351 can you help me add total player in motd. my email: lengoctantoan@gmail.com
