### ISSUE TITLE
Slow on Linux ?

### ISSUE THREAD

**Issue by Guillaume351** [iTXTech/Synapse#30]
Hello,
I tried to run the proxy between three servers on windows, then three servers on Linux Centos 7 64bit (Xeon 1230, 32GB Ram).

On windows, you can't even tell I'm using a proxy. Everything is instant, no delay.
On linux, there it takes 20 extra seconds to join the game, and every interaction takes 4 - 10 seconds to get registered.

Did I setup something wrong ? Is there an explaination ? 

Somebody else from Avengetech told me he has this lag issue.

Thanks

**Comment by PeratX** [comment]
I am using Windows to develop, never tried Synapse on Linux..

**Comment by Guillaume351** [comment]
@PeratX Strange, all servers show 100 TPS / 20 TPS but seems like heartbeat packets and everything is slower

**Comment by PeratX** [comment]
Don't know :(

**Comment by Goodstuff4UonYT** [comment]
Have the same delay, using Linux, too ._.

**Comment by dries-c** [comment]
i am using windows and i dont have this issues

**Comment by Matthww** [comment]
Same problem here... with linux. I tried centos and debian

**Comment by Leejit** [comment]
Where to find a howto for this? I have my SynapseTransfer plugin. I have my Synapse server up, I have it all connected so when my two server are started  the Synapse proxy server reads that they're there... but I don't know how to connect it, or set an ID so I can transfer my players across servers. 

I'm not worried about lag as of yet... I'm sure it'll all be taken care of in the future. For no, id just like to experiment and work with what I have available to be better prepared for when this is a fully functional release.

**Comment by SleepSpace9** [comment]
I'm so happy to read, that I'm not alone with this slow behaviour on linux, I thought it was a misconfiguration or something else on my system.

@LordJoshie you can have a look here https://github.com/iTXTech/Genisys/commit/48f0075b1d325b7576c6dde7a9a2b125fc8f5ffc, I wrote down my steps for testing, but without any warranty. :wink: Hopefully the Wiki pages (https://github.com/iTXTech/Synapse/wiki) will soon be filled.

**Comment by SleepSpace9** [comment]
I tried to put Synapse Server on a Windows machine and left the Genisys Server on the Linux machine (same LAN).This worked for me without delay!

**Comment by Guillaume351** [comment]
@SleepSpace9 And if you do the reverse thing ? Synapse server on Linux and Genisys on Windows ? :p

**Comment by SleepSpace9** [comment]
@Guillaume351 Synapse on Linux and Genisys on Windows brings back the slowness and other strange behaviour.

**Comment by Guillaume351** [comment]
@SleepSpace9 Yeey now we know it's Synapse server side, not synapse client side :/ Any idea @PeratX ?

**Comment by XFuryMCPE** [comment]
So we can put Synapse on windows and Genisys on Linux?

**Comment by PeratX** [comment]
I am adding timings to Synapse to see where is wrong.

**Comment by XFuryMCPE** [comment]
Thanks @PeratX, always here to save the day!

**Comment by Matthww** [comment]
I don't know if it helpful but here is the timings on linux:

https://timings.aikar.co/?url=18612605

Specs:
Intel Xeon E3-1231
2GB ram

Running on ubuntu

**Comment by PeratX** [comment]
@flaxues Are you using the latest version? 
This is mine on Winddows 10 https://timings.aikar.co/?url=18593929

**Comment by PeratX** [comment]
/timings on and wait for sometime, /timings paste

**Comment by Matthww** [comment]
@PeratX I'm using Linux

and ofc i'm on the latest version if I was running a outdated version I couldn't do /timings :P

**Comment by Matthww** [comment]
@PeratX @XFuryMCPE Look at this https://github.com/Hydreon/Mercury/

**Comment by dries-c** [comment]
what!!!???

**Comment by XFuryMCPE** [comment]
http://paste.ubuntu.com/18657932/
https://timings.aikar.co/?url=18657932

Specs:
Intel Xeon E3-1230v2
32gb RAM

**Comment by XFuryMCPE** [comment]
http://paste.ubuntu.com/18657932/
https://timings.aikar.co/?url=18657932

Specs:
Intel Xeon E3-1230v2
32gb RAM

System: Ubuntu 15.04 (GNU/Linux 3.19.0-56-generic x86_64)

Server loads for awhile, then you disconnect. Next time you try to connect it says "Synapse Server: No server online!"

**Comment by Guillaume351** [comment]
@XFuryMCPE Your SlotCombine plugin is very slow, try without it

**Comment by SleepSpace9** [comment]
Here are my timings on Ubuntu Linux 14.04:
https://timings.aikar.co/?url=18688521

**Comment by AndreTheGamer** [comment]
Seems to work fine if you set 

`round(($u[0] / 1024) / 1024, 2)`
to
`round(($u[0] / 1024) / 1024, 5)`

Repeat this for the commons ones.

Before that it was really slow but after editing the above text in ``Server.php`` on Synapse.php it works fine.  I'm running Ubuntu ubuntu 16.04 and i've tested it with below versions such as Ubuntu 15.x and 12.x versions and it works

**Comment by XFuryMCPE** [comment]
Any updates???

**Comment by xZeroMCPE** [comment]
Doesn't seems to be slow for me at all. All it needs is a few customization and a great dedicated server. And it"ll be alright. :+1:

**Comment by PeratX** [comment]
This project is not a long time support project. Please use Nemisys instead later!

**Comment by XFuryMCPE** [comment]
"Seems to work fine if you set

round(($u[0] / 1024) / 1024, 2)
to
round(($u[0] / 1024) / 1024, 5)

Repeat this for the commons ones.

Before that it was really slow but after editing the above text in Server.php on Synapse.php it works fine. I'm running Ubuntu ubuntu 16.04 and i've tested it with below versions such as Ubuntu 15.x and 12.x versions and it works"

Didn't do anything

**Comment by XFuryMCPE** [comment]
If your modification is so good @AndreTheGamer why don't you make it public and do some commits? You'd be helping a ton of people out

**Comment by Leejit** [comment]
I agree. Id like some Synapse for my Linux plz :) lol.

**Comment by SleepSpace9** [comment]
Unfortunately @XFuryMCPE 's trick doesn't work for me (Ubuntu 14.04.4).
I could see, that some packets seem to get lost. I joined the server through Synapse and counted from 1 to 30 in steps of about 1 sec. The result was that some numbers are missing in the output and the numbers which arrived came in one "batch" (with about 3 numbers) after a short break. You can see that at the corresponding timestamp:

```
[01:49:59] [Server thread/INFO]: SleepSpace9 joined the game
[01:50:10] [Server thread/INFO]: <SleepSpace9> 1
[01:50:10] [Server thread/INFO]: <SleepSpace9> 2
[01:50:10] [Server thread/INFO]: <SleepSpace9> 3
[01:50:10] [Server thread/INFO]: <SleepSpace9> 4
[01:50:13] [Server thread/INFO]: <SleepSpace9> 5
[01:50:16] [Server thread/INFO]: <SleepSpace9> 6
[01:50:16] [Server thread/INFO]: <SleepSpace9> 7
[01:50:16] [Server thread/INFO]: <SleepSpace9> 9
[01:50:23] [Server thread/INFO]: <SleepSpace9> 10
[01:50:23] [Server thread/INFO]: <SleepSpace9> 11
[01:50:23] [Server thread/INFO]: <SleepSpace9> 12
[01:50:25] [Server thread/INFO]: <SleepSpace9> 16
[01:50:26] [Server thread/INFO]: <SleepSpace9> 17
[01:50:26] [Server thread/INFO]: <SleepSpace9> 18
[01:50:33] [Server thread/INFO]: <SleepSpace9> 19
[01:50:33] [Server thread/INFO]: <SleepSpace9> 20
[01:50:33] [Server thread/INFO]: <SleepSpace9> 21
[01:50:36] [Server thread/INFO]: <SleepSpace9> 25
[01:50:36] [Server thread/INFO]: <SleepSpace9> 26
[01:50:38] [Server thread/INFO]: <SleepSpace9> 28
[01:50:38] [Server thread/INFO]: <SleepSpace9> 29
[01:50:43] [Server thread/INFO]: <SleepSpace9> 30
[01:50:43] [Server thread/INFO]: <SleepSpace9> 31
[01:50:43] [Server thread/INFO]: <SleepSpace9> 32
```

**Comment by SleepSpace9** [comment]
I can confirm that Nemisys works much better, super fast for me now! :+1: 
Thank you @PeratX!

**Comment by Leejit** [comment]
@SleepSpace9 how do I run the Java on Linux? I wanna test Nemisys. can you teleport a player between worlds yet?

**Comment by SleepSpace9** [comment]
@LordJoshie , no there still seems to be an error in the SynapseTransfer plugin (`/listclients` shows all servers offline ), the function(s) for getting the list of Synapse clients doesn't read the array correctly, because there is one more nested array inside. It's also possibe that Nemisys is sending the $cdata in other format than Synapse. I think it should be reported to @PeratX.
But I was very happy about the new "speed" with Nemisys, I didn't test deeply.

Edit: After I fixed /listclients I'm getting the same error when I try to transfer a player by /transfer command:
`Notice: Undefined index: description in /home/rene/source/SynapseTransfer/src/synapsetransfer/SynapseTransfer.php on line 88`

**Comment by Leejit** [comment]
@SleepSpace9 how'd you set it up tho. I'm new to Java & only have my Linux
vps. I have a desktop installed over it tho. Just need to know what to do

**Comment by SleepSpace9** [comment]
@LordJoshie It's also my first contact with Java, but I had a look at Nukkit (https://github.com/Nukkit/Nukkit). I build a JAR file from Nemisys source as described for Nuckit and started it with 
`java -jar nemisys-1.0dev.jar`
To build the JAR file you'll need JDK 1.8.
