### ISSUE TITLE
can I use it with another plugin?

### ISSUE THREAD

**Issue by vvzar** [iTXTech/Synapse#34]
Like this:
$this->getServer()->getPluginManager()->getPlugin('SynapseTransfer')->transferPlayer($Player,$hash);
?

**Comment by MattWAnderson** [comment]
Yes, please review the sample plugin for an example of code, it can be done without calling on the "SynapseTransfer" plugin as the code is built into the Genysis server.

https://github.com/iTXTech/SynapseTransfer
