### ISSUE TITLE
Synaspe isn't Running

### ISSUE THREAD

**Issue by AppleMinerHD** [iTXTech/Synapse#47]
Everytime i want to do the start.cmd it gives me a issue: Couldn't find a valid Synapse installation and evreytime i do it in the same Folder ist just plopping up for 1 second and disapears and i can't get the phar to put it on my Server How can i get the phar from Synapse on gitter nobody answer me..

**Comment by dries-c** [comment]
use nemisys
synapse is outdate

**Comment by AppleMinerHD** [comment]
Will it be Updated soon? Or never cause i only have php Plugins not Java

**Comment by dries-c** [comment]
synapse dont update!
use nemisys

**Comment by AppleMinerHD** [comment]
But all of my Games & Plugins are based on PhP can i switch with nemisys between php Genisys servers?

**Comment by dries-c** [comment]
you can use nemisys on genisys!

**Comment by MattWAnderson** [comment]
I think you are confused @apple. Run Nemesis on a separate windows server and use the Synapse transfer plugin to link your nemisis (it's a whole separate server and not a plugin) to your SynapseTransfer php plugin on your server.

**Comment by AppleMinerHD** [comment]
Yea im really really bad confused so its right what i understand? Nemisys is working with genisys together?

**Comment by MattWAnderson** [comment]
Nemisys runs as your primary server, clients connect to this and it redirects to your Genisys servers. Nemisys needs to be ran on a Windows machine as it uses Java and mono isn't currently supported for it. Run Nemisys... your Genisys server needs Synapse enabled in the settings with the Nemisys server information. Once done clients will connect to Nemisys and be redirected to the Genisys servers. You can use SynapseTransfer as a plugin on your Genysis servers to allow clients to move between the Genysis servers. Really it's all still development so I wouldn't push it into a working production setup.

**Comment by AppleMinerHD** [comment]
Oh okay thanks that means i cnat't run Nemisys on a Linux vServer ?

**Comment by Matthww** [comment]
@MattWAnderson wait what you don't need MONO to use Nemisys you can just run the command: 'java -jar Nemisys.jar' Nemisys can also be runned on Windows and Linux.

**Comment by Matthww** [comment]
@AppleMinerHD yes you can run Nemisys on Linux

**Comment by MattWAnderson** [comment]
Nemisys runs as your primary server, clients connect to this and it redirects to your Genisys servers. Nemisys needs to be ran on a Windows machine as it uses Java and mono isn't currently supported for it. Run Nemisys... your Genisys server needs Synapse enabled in the settings with the Nemisys server information. Once done clients will connect to Nemisys and be redirected to the Genisys servers. You can use SynapseTransfer as a plugin on your Genysis servers to allow clients to move between the Genysis servers. Really it's all still development so I wouldn't push it into a working production setup.

**Comment by MattWAnderson** [comment]
Sorry, you are correct I was thinking MINET for some reason. :)

**Comment by AppleMinerHD** [comment]
Thanks for helping me out! I Love you ! #nohomo

**Comment by Driesboy** [comment]
#notgay

**Comment by AppleMinerHD** [comment]
Can anyone send me a link to the nemisys.jar i can't find it in the master of Nemisys and i don't know to build a .jar
Sorry about that but please

**Comment by ghost** [comment]
@Driesboy you have telegram? Please you can help me with nemisys in telegram?
