### ISSUE TITLE
Natives?

### ISSUE THREAD

**Issue by ghost** [iTXTech/Synapse#51]
What about implement natives?

I know exist a RakLib native for ALL COMPONENTS, in C and a little things from Velocity: 

https://github.com/VelocityPowered/Velocity/tree/master/native

You know, for performance.

I like projects when are seriosly projects and really good performance built-in.

Edit: Will be a proxy now, right? Not a plugin for Nemisys?

**Comment by PeratX** [comment]
Will consider it after the basic RakNet and Synapse Server is implemented

I have viewed the project you provided.
`zlib` `mbedTLS` are native and the others aren't.
We have `zlib` & `openssl` extension in php, so I don't think we need them.

**Comment by ghost** [comment]
Probably them can be more efficient?

**Comment by PeratX** [comment]
Almost the same.

**Comment by ghost** [comment]
from what i know, php it's so bad on performance, why just not give a chanse? :p try with both

**Comment by PeratX** [comment]
It's not.
The brand-new Synapse will be a high performance server.

**Comment by ghost** [comment]
Ok, will see.

**Comment by ghost** [comment]
And why not create in java, you create in php? Java is FASTER, or c# ? :p i know you know java, idk about c#

**Comment by PeratX** [comment]
Java maybe faster, but it will take more time to development.
We are using [swoole](https://github.com/swoole/swoole-src), coroutine-based concurrency library for PHP.
Server software built on top of it is very fast and efficient, you should review some benchmarks and reports.

**Comment by ghost** [comment]
ok, your decision :)

**Comment by ghost** [comment]
Btw, i don't see any code from "swoole", did you added or?

**Comment by PeratX** [comment]
Swoole is a php extension. See [ide-helper](https://github.com/swoole/ide-helper)

**Comment by ghost** [comment]
Wait a second, "The brand-new Synapse will be a high performance server.", Will be a server software, not a proxy?

**Comment by PeratX** [comment]
proxy server.

**Comment by ghost** [comment]
Ok. I wait commits ;)

**Comment by ghost** [comment]
btw, make them full multithreaded.

**Comment by PeratX** [comment]
This project will be a proxy server framework.
You need to construct a full-featured server by yourself.
Designed to be lightweight, highly extensible.

swoole is using its own multi process model, we don't need to care about how it works.

**Comment by ghost** [comment]
news? @PeratX

**Comment by PeratX** [comment]
50 days before University Entrance Exam.
Considering use single process Coroutine to manage raknet session for better coding experience.

**Comment by ghost** [comment]
ok, i will wait 50 days

**Comment by Erkam246** [comment]
How much days left ?

**Comment by ghost** [comment]
22.

**Comment by Erkam246** [comment]
D:

**Comment by PeratX** [comment]
project suspended.
no need to continue.
easecation choose to improve nemisys

**Comment by Erkam246** [comment]
rip

**Comment by ghost** [comment]
@PeratX i don't like that.

**Comment by ghost** [comment]
@PeratX them will do nothing, i swear. Them do nothing on github from what you can see. It's really hard to work on a good project? :/
