### ISSUE TITLE
Use OpenSSL instead of mcrypt

### ISSUE THREAD

**Issue by ishitatsuyuki** [iTXTech/Synapse#7]
From a experiment, OpenSSL is 200x faster than mcrypt.

Consider switch to that. OpenSSL is included in the docker image.

**Comment by gaoyichuan** [comment]
Have we included OpenSSL in the build script?

**Comment by ishitatsuyuki** [comment]
Seems not, we should remove the line which had disabled it.

**Comment by PeratX** [comment]
Seems using mcrypt is better.

**Comment by PeratX** [comment]
If you want, then you do. I will not provide any support.
