### ISSUE TITLE
Is this working or Not yet?

### ISSUE THREAD

**Issue by TonyWAV** [iTXTech/Synapse#8]

**Comment by ishitatsuyuki** [comment]
No question here. Some people says it works. Try before asking.

**Comment by dries-c** [comment]
how to use?

**Comment by ishitatsuyuki** [comment]
@Driesboy ask on gitter. Stop spamming in issue tracker.

**Comment by dries-c** [comment]
Ok sorry
Op 26-jun.-2016 07:08 schreef "Tatsuyuki Ishi" notifications@github.com:
